### ISSUE TITLE
error in total number of characters

### ISSUE THREAD

**Issue by shreykhetrapal** [abagaini/TidyTuesday#1]
I did this using the tidytext package.
Got the same sum of each letter as you, but the total number of characters are different.

library(tidyverse)
library(tidytext)

netflix_titles <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-04-20/netflix_titles.csv')

my_characters <- c("n","e","t","f","l","i","x")

netflix_titles %>%
  dplyr::select(title) %>% 
  tidytext::unnest_tokens(char, title, token = "characters") %>%
  dplyr::count(char) %>% 
  dplyr::mutate(total = n %>% sum(na.rm = T)) %>% 
  dplyr::filter(char %in% my_characters) %>% 
  dplyr::mutate(freq_percentage = n/total*100) %>% 
  dplyr::arrange(-freq_percentage) %>% 
  dplyr::select(-total)

**Comment by abagaini** [comment]
Dear Shrey,
Thanks for taking the time to look at this. 
So, I looked at the differences in the the types of characters listed from the code you used and my code (I did not use the tidytext package), and in my case, the data frame also contains punctuations, dashes as well as quotation marks (27 extra different "types" of characters) which I take into account in the sum and thus leads to these slight differences.  I guess it depends on the definition of _character_. I hope this addresses the issue.

Alexandra
